-- migration: 01_cargos_niveis.sql
-- Adiciona colunas de auditoria e status aos Cargos existentes
ALTER TABLE public.cargos_permissoes 
ADD COLUMN IF NOT EXISTS status BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- Cria a tabela de Níveis
CREATE TABLE IF NOT EXISTS public.cargo_niveis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo_id BIGINT NOT NULL REFERENCES public.cargos_permissoes(id) ON DELETE RESTRICT,
    nome_nivel TEXT NOT NULL,
    descricao TEXT,
    ordem INTEGER NOT NULL,
    status BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_nivel_por_cargo UNIQUE (cargo_id, nome_nivel),
    CONSTRAINT unique_ordem_por_cargo UNIQUE (cargo_id, ordem)
);

-- Ativa RLS se a aplicação exigir (opcional, deixado disable_rls padrão se não utilizado estritamente)
-- ALTER TABLE public.cargo_niveis ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Permitir leitura/escrita autenticada em niveis" ON public.cargo_niveis FOR ALL TO authenticated USING (true) WITH CHECK (true);
